[package]
name = "rsonpath-benchmarks"
authors = [
    "Mateusz Gienieczko <mat@gienieczko.com>",
    "Charles Paperman <charles.paperman@inria.fr>",
]
version = "0.1.2"
edition = "2021"
description = "Benchmark suite for the `rsonpath` project."
readme = "./README.md"
license = "MIT"
keywords = ["rsonpath", "jsonpath", "query", "simd", "benchmark"]
exclude = ["/data"]
categories = ["text-processing", "development-tools"]
repository = "https://github.com/V0ldek/rsonpath-benchmarks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
criterion = "0.4.0"
eyre = "0.6.8"
jni = { version = "0.19.0", features = ["invocation", "default"] }
libc = "0.2.126"
lazy_static = "1.4.0"
ouroboros = "0.15.5"
rsonpath = { version = "0.1.2", default-features = false }
thiserror = "1.0.37"

[dev-dependencies]
itertools = "0.10.3"
regex = "1.6.0"
memchr = "2.5.0"

[features]
default = ["simd"]
simd = ["rsonpath/simd"]

[build-dependencies]
cc = "1.0"
eyre = "0.6.8"


[[bench]]
name = "ast"
harness = false

[[bench]]
name = "crossref"
harness = false

[[bench]]
name = "openfood"
harness = false

[[bench]]
name = "twitter"
harness = false

[[bench]]
name = "rsonpath_query_compilation"
harness = false